### PR TITLE
implement PROGMEM strings, alignment with ESP_WiFiManager_Lite

### PR DESCRIPTION
**Pull request by hmueller01**

### CODE REVIEW

**Comment by khoih-prog** [comment]
Can you also include in this PR the modification of the examples like [Example fixes #37](https://github.com/khoih-prog/ESP_WiFiManager_Lite/pull/37) to sync with `ESP_WiFiManager_Lite` ?

**Comment by hmueller01** [comment]
Yep. Would give you the chance to release 
```
  1.10.4  K Hoang      27/01/2023  Using PROGMEM for HTML strings
  1.10.5  K Hoang      28/01/2023  Using PROGMEM for strings in examples
```
...

**Comment by khoih-prog** [comment]
I'd prefer to go straight to v1.10.5 than step thru both.

**Comment by khoih-prog** [comment]
I haven't checked, but believe OK to merge now.

**Comment by khoih-prog** [comment]
Hi @hmueller01 

### Release v1.10.5

1. Using PROGMEM for strings in examples. Check [Example fixes #32](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite/pull/32)
2. Using PROGMEM for HTML strings. Check [implement PROGMEM strings, alignment with ESP_WiFiManager_Lite #31](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite/pull/31)
3. Default LittleFS for ESP8266 in examples
4. Improve `README.md` so that links can be used in other sites, such as `PIO`
5. Sync with `ESP_WiFiManager_Lite` v1.10.5

**Pull request merged**
