### PR TITLE
configure use of builtin LED

### PR DESCRIPTION
**Pull request by hmueller01**
Use of a port conflicted with the LED in this lib. So added an option to configure use of builtin LED.

### CODE REVIEW

**Comment by khoih-prog** [comment]
LGTM. Can you also add the option into the other example [**ESPAsync_WiFi_MQTT**](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite/tree/main/examples/ESPAsync_WiFi_MQTT) to save me some time. Then I'll merge.

Thanks,

**Comment by hmueller01** [comment]
Sure. Done. :-)

**Comment by khoih-prog** [comment]
Merged. Will be in next release.

Thanks

**Comment by hmueller01** [comment]
Your last commit [f8eb24c12d0a1f1badffa52022d91f798fc1ddaf](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite/commit/f8eb24c12d0a1f1badffa52022d91f798fc1ddaf) reverted this merged PR. It looks like you took old sources when applying the allman astyle ...

**Pull request merged**
