### PR TITLE
Captive portal

### PR DESCRIPTION
**Pull request by hmueller01**
add CaptivePortal to Config Portal

### CODE REVIEW

**Comment by khoih-prog** [comment]
Hi @hmueller01 

Thanks for your new PR for Captive-Portal.

As this is Async library, I suggest you change to use [**ESPAsyncDNSServer**](https://github.com/khoih-prog/ESPAsyncDNSServer). 

Check the mods in [**ESPAsync_WiFiManager**](https://github.com/khoih-prog/ESPAsync_WiFiManager/releases/tag/v1.13.0) to use AsyncDNSServer instead of DNSServer.

Check the changes in [**Comparing changes**](https://github.com/khoih-prog/ESPAsync_WiFiManager/compare/v1.12.2...v1.13.0)

Waiting for you modified PR.

BR,

**Comment by khoih-prog** [comment]
HI @hmueller01 

Please also help add your PRs into sync twin library [**ESP_WiFiManager_Lite**](https://github.com/khoih-prog/ESP_WiFiManager_Lite)

BR,

**Comment by hmueller01** [comment]
Ah, ok. I didn't knew the [ESP_WiFiManager_Lite](https://github.com/khoih-prog/ESP_WiFiManager_Lite) ...
Maybe I change to this, as I have lots of crashes in my code with ESPAsyncWebServer. Too bad that me-no-dev drops support/development of his excellent work.

I used DNSServer as you already included that (I do not know what the dependency was/is). But ok, you are right. I'll change this in the next days.

**Comment by hmueller01** [comment]
Ok, I switched to AsyncDNSServer. Sync with non Async project [ESP_WiFiManager_Lite](https://github.com/khoih-prog/ESP_WiFiManager_Lite) follows ...

**Comment by khoih-prog** [comment]
Merged. Thanks for your contribution. Looking forward to receiving more PRs from you.

Best Regards,

**Comment by khoih-prog** [comment]
Hi @hmueller01 

The new [**ESPAsync_WiFiManager_Lite releases v1.9.1**](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite/releases/tag/v1.9.1) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite#contributions-and-thanks)

Best Regards,

---

### Release v1.9.1

1. Add `Captive Portal` using AsyncDNSServer. Check [**Captive portal** #22](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite/pull/22)
2. Cleanup reset code. Check [**cleanup reset code** #23](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite/pull/23)
3. Periodical code clean-up

**Pull request merged**
